/*
 * This file is generated by jOOQ.
*/
package de.codepitbull.vertx.scala.jooq.tables;


import de.codepitbull.vertx.scala.jooq.tables.tables.Logs;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in vertx_test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>vertx_test.logs</code>.
     */
    public static final Logs LOGS = de.codepitbull.vertx.scala.jooq.tables.tables.Logs.LOGS;
}
