/*
 * This file is generated by jOOQ.
*/
package de.codepitbull.vertx.scala.jooq.tables;


import de.codepitbull.vertx.scala.jooq.tables.tables.Logs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VertxTest extends SchemaImpl {

    private static final long serialVersionUID = -1470973320;

    /**
     * The reference instance of <code>vertx_test</code>
     */
    public static final VertxTest VERTX_TEST = new VertxTest();

    /**
     * The table <code>vertx_test.logs</code>.
     */
    public final Logs LOGS = de.codepitbull.vertx.scala.jooq.tables.tables.Logs.LOGS;

    /**
     * No further instances allowed
     */
    private VertxTest() {
        super("vertx_test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Logs.LOGS);
    }
}
