MASTER_IP = "192.168.6.7"
NODE_1_IP = "192.168.6.8"
NODE_2_IP = "192.168.6.9"

Vagrant.configure("2") do |config|
  config.vm.synced_folder "shared/", "/shared"
  #config.vm.provision "shell", inline: "apt-get -y install netemul;apt-get -y install ufw;apt-get install systemd"
    
  config.vm.define "m1" do |m1|
    m1.vm.box = "ubuntu/trusty64"
    m1.vm.network "private_network", ip: MASTER_IP
    m1.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        machine_ip: MASTER_IP,
        master_ip: MASTER_IP
      }
    end
    m1.vm.provision "shell", inline: "systemctl restart crmaster"
  end

#  config.vm.define "m2" do |m2|
#    m2.vm.box = "ubuntu/trusty64"
#    m2.vm.network "private_network", ip: NODE_1_IP
#    m2.vm.provision :ansible do |ansible|
#      ansible.limit = "all"
#      ansible.playbook = "playbook.yml"
#      ansible.extra_vars = {
#        machine_ip: NODE_1_IP,
#        master_ip: MASTER_IP
#      }
#    end
#    m2.vm.provision "shell", inline: "systemctl restart crnode"
#  end
#
#  config.vm.define "m3" do |m3|
#    m3.vm.box = "ubuntu/trusty64"
#    m3.vm.network "private_network", ip: NODE_2_IP
#    m3.vm.provision :ansible do |ansible|
#      ansible.limit = "all"
#      ansible.playbook = "playbook.yml"
#      ansible.extra_vars = {
#        machine_ip: NODE_2_IP,
#        master_ip: MASTER_IP
#      }
#    end
#    m3.vm.provision "shell", inline: "systemctl restart crnode"
#  end

end
