NODE_1_IP = "192.168.6.7"
NODE_2_IP = "192.168.6.8"
NODE_3_IP = "192.168.6.9"

Vagrant.configure("2") do |config|
  config.vm.synced_folder "shared/", "/shared"

  config.vm.define "m1" do |m1|
    m1.vm.box = "ubuntu/trusty64"
    m1.vm.network "private_network", ip: NODE_1_IP
    m1.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        node_ip: NODE_1_IP
      }
    end
  end

  config.vm.define "m2" do |m2|
    m2.vm.box = "ubuntu/trusty64"
    m2.vm.network "private_network", ip: NODE_2_IP
    m2.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        master_ip: NODE_1_IP,
        node_ip: NODE_2_IP
      }
    end
  end

  config.vm.define "m3" do |m3|
    m3.vm.box = "ubuntu/trusty64"
    m3.vm.network "private_network", ip: NODE_3_IP
    m3.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        master_ip: NODE_1_IP,
        node_ip: NODE_3_IP
      }
    end
  end

end
