Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared"

  config.vm.define "m1" do |m1|
    m1.vm.box = "ubuntu/trusty64"
    m1.vm.network "private_network", ip: "192.168.6.7"
    m1.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook_java.yml"
    end
  end

end
